"""create interview kits table

Revision ID: 0b972a1118da
Revises: 1c2e42aa7a85
Create Date: 2026-05-01 19:03:32.946604

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0b972a1118da"
down_revision: str | Sequence[str] | None = "1c2e42aa7a85"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "interview_kits",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("candidate_id", sa.UUID(), nullable=False),
        sa.Column("cv_document_id", sa.UUID(), nullable=True),
        sa.Column("job_description_document_id", sa.UUID(), nullable=True),
        sa.Column("candidate_review_id", sa.UUID(), nullable=True),
        sa.Column("candidate_job_match_id", sa.UUID(), nullable=True),
        sa.Column("role_name", sa.String(length=255), nullable=True),
        sa.Column(
            "status", sa.Enum("GENERATED", "FAILED", name="interview_kit_status"), nullable=False
        ),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("technical_questions", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("behavioral_questions", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("risk_based_questions", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("evaluation_rubric", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("source_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["candidate_id"], ["candidates.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["candidate_job_match_id"], ["candidate_job_matches.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["candidate_review_id"], ["candidate_reviews.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["cv_document_id"], ["documents.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["job_description_document_id"], ["documents.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_interview_kits_candidate_id"), "interview_kits", ["candidate_id"], unique=False
    )
    op.create_index(
        op.f("ix_interview_kits_candidate_job_match_id"),
        "interview_kits",
        ["candidate_job_match_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_interview_kits_candidate_review_id"),
        "interview_kits",
        ["candidate_review_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_interview_kits_cv_document_id"), "interview_kits", ["cv_document_id"], unique=False
    )
    op.create_index(
        op.f("ix_interview_kits_job_description_document_id"),
        "interview_kits",
        ["job_description_document_id"],
        unique=False,
    )
    op.execute("ALTER TYPE audit_event_type ADD VALUE IF NOT EXISTS 'INTERVIEW_KIT_CREATED'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_interview_kits_job_description_document_id"), table_name="interview_kits"
    )
    op.drop_index(op.f("ix_interview_kits_cv_document_id"), table_name="interview_kits")
    op.drop_index(op.f("ix_interview_kits_candidate_review_id"), table_name="interview_kits")
    op.drop_index(op.f("ix_interview_kits_candidate_job_match_id"), table_name="interview_kits")
    op.drop_index(op.f("ix_interview_kits_candidate_id"), table_name="interview_kits")
    op.drop_table("interview_kits")
    # ### end Alembic commands ###
