"""create email templates table

Revision ID: 146e0317e533
Revises: 0b972a1118da
Create Date: 2026-05-01 19:15:04.975974

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "146e0317e533"
down_revision: str | Sequence[str] | None = "0b972a1118da"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "email_templates",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column(
            "template_type",
            sa.Enum(
                "SHORTLIST",
                "REJECTION",
                "INTERVIEW_INVITE",
                "ASSIGNMENT_REQUEST",
                "ASSIGNMENT_REMINDER",
                "FOLLOW_UP",
                "OFFER",
                "GENERAL",
                name="email_template_type",
            ),
            nullable=False,
        ),
        sa.Column("subject_template", sa.String(length=500), nullable=False),
        sa.Column("body_template", sa.Text(), nullable=False),
        sa.Column("required_variables", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("optional_variables", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_email_templates_name"), "email_templates", ["name"], unique=False)
    op.create_index(
        op.f("ix_email_templates_template_type"), "email_templates", ["template_type"], unique=False
    )
    op.execute("ALTER TYPE audit_event_type ADD VALUE IF NOT EXISTS 'EMAIL_TEMPLATE_CREATED'")
    op.execute("ALTER TYPE audit_event_type ADD VALUE IF NOT EXISTS 'EMAIL_TEMPLATE_UPDATED'")
    op.execute("ALTER TYPE audit_event_type ADD VALUE IF NOT EXISTS 'EMAIL_TEMPLATE_RENDERED'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_email_templates_template_type"), table_name="email_templates")
    op.drop_index(op.f("ix_email_templates_name"), table_name="email_templates")
    op.drop_table("email_templates")
    # ### end Alembic commands ###
