"""create documents table

Revision ID: 189bbbe68063
Revises: c68abf217f61
Create Date: 2026-04-26 13:12:32.997258

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "189bbbe68063"
down_revision: str | Sequence[str] | None = "c68abf217f61"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "documents",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("original_filename", sa.String(length=500), nullable=False),
        sa.Column("storage_path", sa.String(length=1000), nullable=False),
        sa.Column("content_type", sa.String(length=255), nullable=False),
        sa.Column("file_size", sa.Integer(), nullable=False),
        sa.Column(
            "document_type",
            sa.Enum(
                "CV", "JOB_DESCRIPTION", "POLICY", "ASSIGNMENT", "GENERAL", name="document_type"
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("UPLOADED", "PROCESSING", "PROCESSED", "FAILED", name="document_status"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("documents")
    # ### end Alembic commands ###
