"""create candidate reviews table

Revision ID: 1ab5f21411f2
Revises: 6d5901d34e97
Create Date: 2026-04-30 17:59:09.121373

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1ab5f21411f2"
down_revision: str | Sequence[str] | None = "6d5901d34e97"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "candidate_reviews",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("candidate_id", sa.UUID(), nullable=False),
        sa.Column("agent_run_id", sa.UUID(), nullable=True),
        sa.Column("cv_document_id", sa.UUID(), nullable=True),
        sa.Column("role_applied_for", sa.String(length=255), nullable=True),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("score", sa.Integer(), nullable=True),
        sa.Column(
            "recommendation",
            sa.Enum("SHORTLIST", "HOLD", "REJECT", name="candidate_review_recommendation"),
            nullable=False,
        ),
        sa.Column(
            "confidence",
            sa.Enum("LOW", "MEDIUM", "HIGH", name="candidate_review_confidence"),
            nullable=False,
        ),
        sa.Column("strengths", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("risks", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("interview_focus_areas", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("source_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["agent_run_id"], ["agent_runs.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["candidate_id"], ["candidates.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["cv_document_id"], ["documents.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_candidate_reviews_agent_run_id"),
        "candidate_reviews",
        ["agent_run_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_candidate_reviews_candidate_id"),
        "candidate_reviews",
        ["candidate_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_candidate_reviews_cv_document_id"),
        "candidate_reviews",
        ["cv_document_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_candidate_reviews_cv_document_id"), table_name="candidate_reviews")
    op.drop_index(op.f("ix_candidate_reviews_candidate_id"), table_name="candidate_reviews")
    op.drop_index(op.f("ix_candidate_reviews_agent_run_id"), table_name="candidate_reviews")
    op.drop_table("candidate_reviews")
    # ### end Alembic commands ###
