"""create candidate job matches table

Revision ID: 1c2e42aa7a85
Revises: 4c032b7d4c36
Create Date: 2026-05-01 17:29:31.073615

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1c2e42aa7a85"
down_revision: str | Sequence[str] | None = "4c032b7d4c36"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "candidate_job_matches",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("candidate_id", sa.UUID(), nullable=False),
        sa.Column("cv_document_id", sa.UUID(), nullable=False),
        sa.Column("job_description_document_id", sa.UUID(), nullable=False),
        sa.Column("role_name", sa.String(length=255), nullable=True),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("match_score", sa.Integer(), nullable=False),
        sa.Column(
            "recommendation",
            sa.Enum(
                "STRONG_MATCH",
                "MATCH",
                "PARTIAL_MATCH",
                "NOT_RECOMMENDED",
                name="candidate_job_match_recommendation",
            ),
            nullable=False,
        ),
        sa.Column(
            "confidence",
            sa.Enum("LOW", "MEDIUM", "HIGH", name="candidate_job_match_confidence"),
            nullable=False,
        ),
        sa.Column("matched_skills", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("missing_skills", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("risks", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("interview_focus_areas", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("source_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["candidate_id"], ["candidates.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["cv_document_id"], ["documents.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["job_description_document_id"], ["documents.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_candidate_job_matches_candidate_id"),
        "candidate_job_matches",
        ["candidate_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_candidate_job_matches_cv_document_id"),
        "candidate_job_matches",
        ["cv_document_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_candidate_job_matches_job_description_document_id"),
        "candidate_job_matches",
        ["job_description_document_id"],
        unique=False,
    )
    op.execute("ALTER TYPE audit_event_type ADD VALUE IF NOT EXISTS 'CANDIDATE_JOB_MATCH_CREATED'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_candidate_job_matches_job_description_document_id"),
        table_name="candidate_job_matches",
    )
    op.drop_index(
        op.f("ix_candidate_job_matches_cv_document_id"), table_name="candidate_job_matches"
    )
    op.drop_index(op.f("ix_candidate_job_matches_candidate_id"), table_name="candidate_job_matches")
    op.drop_table("candidate_job_matches")
    # ### end Alembic commands ###
