"""create messages table

Revision ID: 215d0a0f4418
Revises: dee5540be950
Create Date: 2026-04-26 01:08:36.024705

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "215d0a0f4418"
down_revision: str | Sequence[str] | None = "dee5540be950"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
