"""add extracted text to documents

Revision ID: 37e3addfc765
Revises: 94bbc48578c4
Create Date: 2026-04-26 15:05:21.500196

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "37e3addfc765"
down_revision: str | Sequence[str] | None = "94bbc48578c4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("documents", sa.Column("extracted_text", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("documents", "extracted_text")
    # ### end Alembic commands ###
