"""create outbox messages table

Revision ID: 6d5901d34e97
Revises: f338194bf74b
Create Date: 2026-04-30 17:21:35.900237

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "6d5901d34e97"
down_revision: str | Sequence[str] | None = "f338194bf74b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
