"""create documents table

Revision ID: 7b9f5e44312a
Revises: 189bbbe68063
Create Date: 2026-04-26 14:55:02.471630

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "7b9f5e44312a"
down_revision: str | Sequence[str] | None = "189bbbe68063"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
