"""create candidates table

Revision ID: 85ddd6f9e50e
Revises: 9d70ccca7dee
Create Date: 2026-04-27 21:11:14.356505

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "85ddd6f9e50e"
down_revision: str | Sequence[str] | None = "9d70ccca7dee"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "candidates",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("full_name", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("phone", sa.String(length=50), nullable=True),
        sa.Column("role_applied_for", sa.String(length=255), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "NEW",
                "REVIEWING",
                "SHORTLISTED",
                "REJECTED",
                "INTERVIEWING",
                "HIRED",
                name="candidate_status",
            ),
            nullable=False,
        ),
        sa.Column("cv_document_id", sa.UUID(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["cv_document_id"], ["documents.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_candidates_cv_document_id"), "candidates", ["cv_document_id"], unique=False
    )
    op.create_index(op.f("ix_candidates_email"), "candidates", ["email"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_candidates_email"), table_name="candidates")
    op.drop_index(op.f("ix_candidates_cv_document_id"), table_name="candidates")
    op.drop_table("candidates")
    # ### end Alembic commands ###
