"""create documents table

Revision ID: 94bbc48578c4
Revises: c0b1bd7fbe18
Create Date: 2026-04-26 14:57:59.624009

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "94bbc48578c4"
down_revision: str | Sequence[str] | None = "c0b1bd7fbe18"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
