"""add embedding to document chunks

Revision ID: 9d70ccca7dee
Revises: 5c008ad37c17
Create Date: 2026-04-26 16:07:31.023572

"""

from collections.abc import Sequence

import sqlalchemy as sa
from pgvector.sqlalchemy import Vector

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9d70ccca7dee"
down_revision: str | Sequence[str] | None = "5c008ad37c17"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "document_chunks",
        sa.Column("embedding", Vector(768), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("document_chunks", "embedding")
    # ### end Alembic commands ###
