"""create documents table

Revision ID: c0b1bd7fbe18
Revises: 7b9f5e44312a
Create Date: 2026-04-26 14:55:16.060502

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "c0b1bd7fbe18"
down_revision: str | Sequence[str] | None = "7b9f5e44312a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
