"""create outbox messages table

Revision ID: f338194bf74b
Revises: 25144525b9a6
Create Date: 2026-04-30 17:17:34.451238

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f338194bf74b"
down_revision: str | Sequence[str] | None = "25144525b9a6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "outbox_messages",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("approval_request_id", sa.UUID(), nullable=True),
        sa.Column("candidate_id", sa.UUID(), nullable=True),
        sa.Column("recipient_email", sa.String(length=255), nullable=True),
        sa.Column("subject", sa.String(length=500), nullable=True),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("PENDING", "SENT", "FAILED", name="outbox_message_status"),
            nullable=False,
        ),
        sa.Column("provider_message_id", sa.String(length=255), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["approval_request_id"], ["approval_requests.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["candidate_id"], ["candidates.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_outbox_messages_approval_request_id"),
        "outbox_messages",
        ["approval_request_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_outbox_messages_candidate_id"), "outbox_messages", ["candidate_id"], unique=False
    )
    op.create_index(op.f("ix_outbox_messages_status"), "outbox_messages", ["status"], unique=False)
    op.execute("ALTER TYPE audit_event_type ADD VALUE IF NOT EXISTS 'OUTBOX_CREATED'")
    op.execute("ALTER TYPE audit_event_type ADD VALUE IF NOT EXISTS 'OUTBOX_MARKED_SENT'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_outbox_messages_status"), table_name="outbox_messages")
    op.drop_index(op.f("ix_outbox_messages_candidate_id"), table_name="outbox_messages")
    op.drop_index(op.f("ix_outbox_messages_approval_request_id"), table_name="outbox_messages")
    op.drop_table("outbox_messages")
    # ### end Alembic commands ###
